SE [master]
GO

/****** Object:  Database [GXLAN]    Script Date: 12/06/2023 09:28:23 ******/
CREATE DATABASE [GXLAN]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GXLAN', FILENAME = N'E:\SQL Server\Data\GXLAN.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GXLAN_log', FILENAME = N'E:\SQL Server\Data\GXLAN_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GXLAN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GXLAN] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GXLAN] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GXLAN] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GXLAN] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GXLAN] SET ARITHABORT OFF 
GO

ALTER DATABASE [GXLAN] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [GXLAN] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GXLAN] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GXLAN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GXLAN] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GXLAN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GXLAN] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GXLAN] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GXLAN] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GXLAN] SET  ENABLE_BROKER 
GO

ALTER DATABASE [GXLAN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GXLAN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GXLAN] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GXLAN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GXLAN] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GXLAN] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [GXLAN] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GXLAN] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GXLAN] SET  MULTI_USER 
GO

ALTER DATABASE [GXLAN] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GXLAN] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GXLAN] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GXLAN] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GXLAN] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GXLAN] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [GXLAN] SET QUERY_STORE = OFF
GO

ALTER DATABASE [GXLAN] SET  READ_WRITE 
GO



USE [GXLAN]
GO

/****** Object:  Table [dbo].[LCT0001]    Script Date: 12/06/2023 09:35:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LCT0001](
	[ID] [nchar](20) NOT NULL,
	[Data] [datetime] NOT NULL,
	[Hora] [nchar](8) NOT NULL,
	[Valor] [money] NOT NULL,
	[Tipo] [nchar](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[Data] ASC,
	[Hora] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


